name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    strategy:
      matrix:
        #repo: [vulkan,wayland,X11,glfw,cimgui,spirv,glslang,shaderc]
        repo: [vulkan,wayland]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: tiawl/spaceporn-dep-action-ci@v1
      with:
        user: ${{ matrix.repo }}
