name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    strategy:
      matrix:
        #repo: [vulkan,wayland,X11,glfw,cimgui,spirv,glslang,shaderc]
        repo: [vulkan,wayland,X11,glfw]
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-dep-action-ci@v1
      with:
        user: ${{ matrix.repo }}.zig
        test_build: 'false'
        test_update: 'true'
        test_fetch: 'true'
