name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    strategy:
      matrix:
        repo:
          - vulkan
          - wayland
          - X11
          - glfw
          - cimgui
          - spirv
          - glslang
          - shaderc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: sha
      shell: bash
      run: |
        printf 'head=%s\n' "$(git rev-parse HEAD)" >> "${GITHUB_OUTPUT}"
    - uses: tiawl/spaceporn-action-ci@43df9f0e7253ba1ada2ff1882a5ac636be43d4eb
      with:
        repository: "${{ github.repository }}"
        additional_zig_opts: "${{ matrix.repo == 'cimgui' && '-Dplatform=GLFW -Drenderer=Vulkan' || '' }}"
        sha: "${{ steps.sha.output.head }}"
        user: "${{ matrix.repo }}.zig"
        token: "${{ github.token }}"
        test_build: 'false'
        test_update: 'true'
        test_fetch: 'true'
